name: Main
on: push
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.5, 2.6]
    env: 
      CI: true
    steps:
    - uses: actions/checkout@master

    # Setup ruby dependencies
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ruby }}-
    - name: bundle install
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    # Setup node dependencies
    - uses: actions/setup-node@v2-beta
      with:
        node-version: 12.x
    - id: yarn-cache
      run: echo "::set-output name=directory::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.directory }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install --frozen-lockfile

    # Actually run tests and lint
    - run: |
        yarn lint
        yarn print --check '**/*'
        yarn test
        bundle exec rake test
